
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app

  frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - "3001:3000"
      volumes:
        - ./frontend:/usr/src/app

  databse:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - ./database/DjangoWork:/usr/src/app
      - ./database/DjangoWork/db.sqlite3:/usr/src/app/db.sqlite3

